100-hours-a-week/20-real-cloud

README.md
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> 📝 docs: 테라폼 협업 가이드 README.md에 추가

README.md
- 네이밍 규칙 추가
- 오타 수정
- 가독성 개선
- Fixes #28 
1. [네이밍 규칙 추가]
2. [오타 수정]
3. [가독성 개선]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> 📝 docs: README.md 수정

README.md
Tag 룰 수정 (Name tag 추가)
Tag 룰 수정 (Name tag 추가)
- Fixes #28 
1. [Tag Rule에 Name 태그 추가]
-> 콘솔 상에서 리소스 명을 표기하기 위함
=> 📝 docs: README 수정

terraform/v1/modules/compute/main.tf, terraform/v1/modules/compute/outputs.tf, terraform/v1/modules/compute/variables.tf
- ec2 기본 모듈 작성
- ec2_id, ec2_public_ip outputs 작성
- 기본 variable 설정
ec2 기본 모듈 작성 완료
- Resolves #32 
1. ec2 기본 모듈, output, variable 작성
x
1. terraform fmt  완료
기본 모듈이어서 terraform validate 및 terraform plan은 수행하지 못하였습니다.
=> ✨ feat: Terraform ec2 module

.gitmodules
submoudle 세팅 완료
- Closes #53 
1. submodule 추가
git pull 이후
git submodule update --init --recursive
입력하면 서브모듈 초기화 가능
=> ✨ faet: update submoudle

terraform/v1/envs/mvp/locals.tf, terraform/v1/envs/mvp/main.tf, terraform/v1/envs/mvp/variables.tf
Terraform tag 자동화 구현
- Refactor #28 
1. 수동으로 태그 입력하는 것이 아닌, 자동화를 구현
2. `terraform plan`이나 `terraform apply` 할 때, Assignee만 입력하면 됨 (nilla, river, denver)
---
1. 로컬 테스트 진행함
아직까지 리팩토링 해야될 여지가 있음. 아직 좀 난잡한 느낌...?
=> ✨ feat: terraform tag 자동화 구현

terraform/v1/envs/mvp/main.tf, terraform/v1/envs/mvp/variables.tf, terraform/v1/modules/network/locals.tf, terraform/v1/modules/network/main.tf, terraform/v1/modules/network/variables.tf, terraform/v1/modules/security/locals.tf, terraform/v1/modules/security/main.tf, terraform/v1/modules/security/variables.tf
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> ✨feat: Terraform tag 기능 추가

terraform/v1/envs/mvp/main.tf, terraform/v1/envs/mvp/outputs.tf, terraform/v1/envs/mvp/variables.tf, terraform/v1/envs/mvp/versions.tf
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> ♻️ refactor : 주석 제거 및 versions.tf 수정

terraform/v1/modules/compute/locals.tf, terraform/v1/modules/compute/main.tf, terraform/v1/modules/network/variables.tf, terraform/v1/modules/security/variables.tf
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> ♻️ refactor : compute 모듈 태그 자동화 및 주석 처리

terraform/v1/envs/mvp/main.tf, terraform/v1/modules/compute/locals.tf, terraform/v1/modules/compute/main.tf, terraform/v1/modules/network/variables.tf, terraform/v1/modules/security/variables.tf
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> ♻️ refactor : compute 모듈 태그 추가

terraform/v1/envs/mvp/main.tf, terraform/v1/envs/mvp/variables.tf, terraform/v1/modules/compute/main.tf, terraform/v1/modules/compute/variables.tf, terraform/v1/modules/security/main.tf, terraform/v1/modules/security/outputs.tf, terraform/v1/modules/security/variables.tf, terraform/v1/modules/storage/main.tf, terraform/v1/modules/storage/outputs.tf, terraform/v1/modules/storage/variables.tf
백엔드에 연결할 이미지 & 로그 저장소용 모듈을 추가하였습니다
- Resolves #62 
1. storage 모듈에 s3 모듈을 추가
- s3 기본 생성 ( acl , versioning on, log expiration 30일, 암호화 설정 완료)
- s3 버킷 정책 생성 (ec2에 연결된 iam role에 한해 img는 조회 및 이미지 가져오기가 가능 / log는 읽기 쓰기 지우기 가능)
2. security 모듈에 ec2 iam용 ec2_assume, iam role, iam instance profile 생성
아직 ec2 모듈을 main에서 호출하고 있지 않으므로 refactor 브랜치 새로 만들어서 ec2 모듈 호출작업을 진행할 생각임
=> ✨ feat: Terraform s3 for backend&log module

terraform/v1/backend/main.tf, terraform/v1/envs/mvp/main.tf, terraform/v1/envs/mvp/variables.tf, terraform/v1/modules/compute/main.tf, terraform/v1/modules/compute/variables.tf
- Resolves #64
1. ec2 모듈을 main에서 호출하였습니다.
2. iam role 프로필 및 security group을 ec2가 주입받도록 변경하였습니다. 
3. tagging이 제대로 적용되도록 오타 및 variable 값을 변경하였습니다.
=> ♻️ refactor : compute 모듈 호출 및 iam role 주입, 태깅 오타 수정

terraform/v1/envs/mvp/main.tf, terraform/v1/envs/mvp/variables.tf, terraform/v1/modules/cdn/main.tf, terraform/v1/modules/cdn/ouputs.tf, terraform/v1/modules/cdn/variables.tf, terraform/v1/modules/iam/main.tf, terraform/v1/modules/iam/outputs.tf, terraform/v1/modules/storage/main.tf, terraform/v1/modules/storage/outputs.tf, terraform/v1/modules/storage/variables.tf
- Resolves #71 
1. 정적 웹사이트 호스팅용 s3를 이미지 정적 서빙용 s3로 변경(oai,cors,정적호스팅 설정 삭제 / oac 설정, 버킷 정책 설정)
2. 이미지+로그 저장용 s3를 로그 저장소용 s3로 변경 (이미지 경로 및 prefix 없애고 로그 권한만 남김)
3. cloudfront 오리진 설정 변경 (/images/ 경로)
4. oac, oai 설정 확인
5. log 버킷에는 ec2가 put 가능하도록 정책 / static 버킷에는 cloudfront는 get, ec2는 listbucket,get,put,delete 가능하도록 정책 변경
=> ♻️ refactor : cloudfront + s3 module fix

terraform/v1/envs/mvp/main.tf, terraform/v1/envs/mvp/outputs.tf, terraform/v1/envs/mvp/variables.tf, terraform/v1/modules/cdn/main.tf, terraform/v1/modules/network/main.tf, terraform/v1/modules/network/outputs.tf, terraform/v1/modules/network/variables.tf, terraform/v1/modules/storage/main.tf
- Resolves #73 
1. s3 static 버킷의 acl 삭제
2. alb az 하나 더 추가
3. name prefix 대문자에서 소문자로 변경
4. cloudfront oai prefix 때문에 oac가 있음에도 누락으로 판단하는 현상 해결
5. allowed_methods CloudFront가 허용하는 정확한 조합으로 변경
6. acm 리전 분리
4. terraform apply 후 destroy 진행
=> 🐛 fix : apply bug fix

terraform/v1/modules/storage/main.tf
static s3에 파괴방지 추가
- Resolves #75 
1. static s3에 파괴방지 추가
1. terraform fmt
2. terraform validate
3. terraform plan
=> ♻️ refactor  : s3 prevent destroy

terraform/v1/modules/cdn/main.tf
1. Route 53을 CloudFront에 연결
2. 도메인 등록 
- Resolves #36 
1. Route 53을 CloudFront에 연결
2. 도메인 등록 및 레코드 연결
=> ✨ feat: Add Route53 configuration module

terraform/v1/modules/cdn/main.tf
1. route 53 버그 수정
2. 서브모듈 내의 domain_name 변수 수정
- Fixes #36 
1. `ttl = 300` -> 삭제
2. `domain_name = www.kakaotech.com` -> `domain_name = kakaotech.com`
1. terraform plan을 통한 리소스 정보 확인
=> 🐛 fix: route 53 버그 수정

terraform/v1/modules/cdn/main.tf, terraform/v1/modules/compute/main.tf
- Resolves #83 
1. 클라우드 프론트 path pattern 변경
2. ec2 파괴 방지 및 ami 변경
3. 삭제 스크립트 추가
=> Feat/refactor module/83

terraform/v1/envs/mvp/main.tf, terraform/v1/envs/mvp/variables.tf, terraform/v1/modules/cdn/main.tf, terraform/v1/modules/cdn/variables.tf, terraform/v1/modules/storage/main.tf
도메인 명 CloudFront와 Route 53 둘 다 정상적으로 연동되게 수정
- Refactor #36 
1. domain_name 변수 -> apex_domain_name로 변경
2. CloudFront에도 반영
3.`aws_cloudfront_distribution` 리소스의 `aliases` 변수에 `kakaotech.com`와 `www.kakaotech.com` 추가
1. terraform plan 적용
=> ♻️ refactor: 도메인 이름 세분화

terraform/v1/modules/cdn/main.tf
cdn 모듈 내부 S3와 관련된 url 수정
- Chore #71 
1. `path_pattern = /_static/*` -> `path_pattern = /static/*` 으로 수정
=> 🙈 chore: CloudFront distribution S3 URL 수정

terraform/v1/envs/mvp/main.tf, terraform/v1/envs/mvp/variables.tf, terraform/v1/modules/cdn/main.tf, terraform/v1/modules/cdn/variables.tf, terraform/v1/modules/compute/main.tf, terraform/v1/modules/compute/outputs.tf, terraform/v1/modules/compute/variables.tf, terraform/v1/modules/network/main.tf
클라우드 프론트 -> alb -> ec2 로 진행되던 로직을
클라우드 프론트 -> ec2로 변경
- Resolves #87 
1. 클라우드 프론트 -> ec2로 변경
4. terraform apply 후 curl 진행
=> ♻️ refactor : change cloudfront origin to ec2
